# Generated by Django 2.1.5 on 2021-07-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='header',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
